domain = "example.com"
pfxFolder = "D:\\Certs\\your_domain"
pfxFile = "your_domain.pfx"
pfxPassword = "yourstrongpassWORd!1234567"
wacsPath = "D:\\wacs.exe"
cfEnvVarName = "CLOUDFLARE_API_TOKEN"
email = "your@example.com"